const components=[
 {id:1,cat:'CPU',brand:'AMD',name:'Ryzen 7 7800X3D',price:7990000,spec:'8 nhân · AM5 · 120W',socket:'AM5',memory:null,watts:120},
 {id:2,cat:'CPU',brand:'Intel',name:'Core i5-14600K',price:7490000,spec:'14 nhân · LGA1700 · 181W',socket:'LGA1700',memory:null,watts:181},
 {id:3,cat:'Motherboard',brand:'MSI',name:'MAG B650M Mortar WiFi',price:4290000,spec:'AM5 · DDR5 · mATX',socket:'AM5',memory:'DDR5',form:'mATX',watts:70},
 {id:4,cat:'Motherboard',brand:'ASUS',name:'TUF Gaming B760-PLUS',price:4690000,spec:'LGA1700 · DDR5 · ATX',socket:'LGA1700',memory:'DDR5',form:'ATX',watts:70},
 {id:5,cat:'RAM',brand:'Kingston',name:'Fury Beast 32GB DDR5',price:2890000,spec:'32GB · 6000MHz · DDR5',memory:'DDR5',watts:10},
 {id:6,cat:'RAM',brand:'Corsair',name:'Vengeance 32GB DDR4',price:1890000,spec:'32GB · 3200MHz · DDR4',memory:'DDR4',watts:10},
 {id:7,cat:'GPU',brand:'NVIDIA',name:'GeForce RTX 4070 SUPER',price:17490000,spec:'12GB · sẵn sàng 2K · 220W',watts:220,clearance:305},
 {id:8,cat:'GPU',brand:'AMD',name:'Radeon RX 7800 XT',price:13990000,spec:'16GB · sẵn sàng 2K · 263W',watts:263,clearance:310},
 {id:9,cat:'SSD',brand:'Samsung',name:'990 PRO 1TB NVMe',price:2190000,spec:'1TB · Gen4 · 7450MB/s',watts:8},
 {id:10,cat:'PSU',brand:'Corsair',name:'RM850e 850W Gold',price:2690000,spec:'850W · 80+ Gold · Modular',watts:850},
 {id:11,cat:'Case',brand:'Lian Li',name:'LANCOOL 216',price:2490000,spec:'ATX · hỗ trợ GPU 392mm',form:'ATX',clearance:392},
 {id:12,cat:'CPU Cooler',brand:'DeepCool',name:'AK620 Digital',price:1690000,spec:'AM5 / LGA1700 · 260W',sockets:['AM5','LGA1700'],watts:5}
];
const builds=[['Gaming 15M','High-FPS 1080p gaming','Ryzen 5 7600','RTX 4060','16GB DDR5','15.490.000'],['Gaming 30M','Smooth 2K AAA gaming','Ryzen 7 7800X3D','RTX 4070 SUPER','32GB DDR5','30.890.000'],['Programming 20M','Fast development workstation','Core i5-14600K','RTX 4060','32GB DDR5','20.490.000'],['Design 30M','Creative work & editing','Ryzen 7 7800X3D','RX 7800 XT','32GB DDR5','29.990.000']];
const $=s=>document.querySelector(s), money=n=>`${Number(n).toLocaleString('vi-VN')} VNĐ`;
const usageLabels={Gaming:'Chơi game',Office:'Văn phòng',Programming:'Lập trình',Design:'Đồ họa',Editing:'Dựng video',Streaming:'Livestream'};
function componentCard(c){return `<article class="component-card"><div class="component-art ${c.cat.toLowerCase().replace(' ','-')}"><span>${c.cat}</span></div><p class="category">${c.cat} · ${c.brand}</p><h3>${c.name}</h3><p class="muted">${c.spec}</p><div class="card-bottom"><b>${money(c.price)}</b><button class="icon-button detail" data-id="${c.id}" aria-label="Xem chi tiết">↗</button></div></article>`}
function renderComponents(){let list=[...components],filter=$('#component-filter').value,sort=$('#component-sort').value;if(filter!=='All')list=list.filter(c=>c.cat===filter);if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);$('#component-grid').innerHTML=list.map(componentCard).join('');document.querySelectorAll('.detail').forEach(b=>b.onclick=()=>showToast(`${components.find(c=>c.id==b.dataset.id).name}: contact us for full specifications and availability.`))}
function renderBuilds(){$('#build-cards').innerHTML=builds.map((b,i)=>`<article class="build-card"><div class="build-art art-${i}"><span>${String(i+1).padStart(2,'0')}</span></div><p class="category">${b[0]}</p><h3>${b[1]}</h3><dl><dt>CPU</dt><dd>${b[2]}</dd><dt>GPU</dt><dd>${b[3]}</dd><dt>RAM</dt><dd>${b[4]}</dd></dl><div class="card-bottom"><b>${b[5]} triệu</b><button class="text-button" data-build="${b[0]}">Xem chi tiết →</button></div></article>`).join('');document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>{$('#contact-build').value=b.dataset.build;location.hash='contact'})}
const cats=['CPU','Motherboard','RAM','GPU','SSD','PSU','Case','CPU Cooler'];
const catLabels={CPU:'Bộ xử lý',Motherboard:'Bo mạch chủ',RAM:'RAM',GPU:'Card đồ họa',SSD:'Ổ cứng SSD',PSU:'Nguồn',Case:'Vỏ máy', 'CPU Cooler':'Tản nhiệt CPU'};
function renderBuilder(){$('#builder-categories').innerHTML=cats.map(cat=>`<section class="builder-category"><h3>${catLabels[cat]}<small>Chọn 1</small></h3>${components.filter(c=>c.cat===cat).map(c=>`<label class="part-row"><input type="radio" name="cat-${cat}" value="${c.id}"><span>${c.name}<small>${c.spec}</small></span><b>${money(c.price)}</b></label>`).join('')||'<p class="empty">Chưa có linh kiện.</p>'}</section>`).join('');document.querySelectorAll('.part-row input').forEach(i=>i.onchange=updateBuilder)}
function updateBuilder(){let selected=[...document.querySelectorAll('.part-row input:checked')].map(i=>components.find(c=>c.id==i.value)),total=selected.reduce((s,c)=>s+c.price,0);$('#builder-total').textContent=money(total);$('#summary-items').innerHTML=cats.map(cat=>{let c=selected.find(x=>x.cat===cat);return `<div class="summary-row"><span>${catLabels[cat]}</span><b>${c?c.name:'Chưa chọn'}</b></div>`}).join('');let issues=[];let cpu=selected.find(c=>c.cat==='CPU'),board=selected.find(c=>c.cat==='Motherboard'),ram=selected.find(c=>c.cat==='RAM'),psu=selected.find(c=>c.cat==='PSU'),cooler=selected.find(c=>c.cat==='CPU Cooler');if(cpu&&board&&cpu.socket!==board.socket)issues.push('Socket CPU không tương thích với bo mạch chủ.');if(board&&ram&&board.memory!==ram.memory)issues.push('Loại RAM không tương thích với bo mạch chủ.');if(cpu&&cooler&&!cooler.sockets.includes(cpu.socket))issues.push('Tản nhiệt CPU không hỗ trợ socket này.');if(psu&&selected.reduce((s,c)=>s+(c.watts||0),0)>psu.watts*.7)issues.push('Công suất nguồn không đủ cho cấu hình này.');$('#compatibility').innerHTML=issues.length?`<strong>⚠ Lỗi tương thích</strong>${issues.map(x=>`<p>${x}</p>`).join('')}`:'<strong class="ok">✓ Đã kiểm tra tương thích</strong><p>Chưa phát hiện lỗi nghiêm trọng trong các linh kiện đã chọn.</p>';$('#compat-status').textContent=issues.length?'⚠ Cần xem lại':'● Tương thích';$('#compat-status').className=issues.length?'danger':''}
function showToast(text){let t=document.createElement('div');t.className='toast';t.textContent=text;document.body.append(t);setTimeout(()=>t.remove(),3500)}
let advisorStep=0;function showAdvisorStep(){document.querySelectorAll('.advisor-step').forEach((s,i)=>s.classList.toggle('active',i===advisorStep));document.querySelectorAll('.progress span').forEach((s,i)=>s.classList.toggle('active',i<=advisorStep));$('#advisor-back').style.visibility=advisorStep?'visible':'hidden';$('#advisor-next').innerHTML=advisorStep===3?'Chọn cấu hình →':'Tiếp tục →';if(advisorStep===3)renderRecommendations()}
function renderRecommendations(){let usage=$('input[name=usage]:checked').value,budget=Number($('input[name=budget]:checked').value),base=budget>30000000?components[0]:components[1];$('#recommendations').innerHTML=[['Đáng tiền nhất',base,components[6],Math.round(budget*.82)],['Cân bằng',base,components[7],Math.round(budget*.96)],['Hiệu năng cao',components[0],components[6],Math.round(budget*1.12)]].map(x=>`<article class="recommendation"><div class="rec-heading"><b>${x[0]}</b><small>${usageLabels[usage]} · cấu hình đề xuất</small></div><p><strong>CPU</strong> ${x[1].name}<br><strong>GPU</strong> ${x[2].name}<br><strong>RAM</strong> 32GB DDR5 · 1TB NVMe</p><div class="rec-footer"><b>${money(x[3])}</b><button class="text-button choose-build">Chọn cấu hình này →</button></div></article>`).join('');document.querySelectorAll('.choose-build').forEach(b=>b.onclick=()=>{location.hash='contact';showToast('Đã chọn cấu hình. Hãy hoàn tất biểu mẫu bên dưới.')})}
$('#advisor-next').onclick=()=>{if(advisorStep<3)advisorStep++;showAdvisorStep()};$('#advisor-back').onclick=()=>{if(advisorStep>0)advisorStep--;showAdvisorStep()};$('#component-filter').onchange=renderComponents;$('#component-sort').onchange=renderComponents;
function selectedBuild(){return [...document.querySelectorAll('.part-row input:checked')].map(i=>components.find(c=>c.id==i.value)).filter(Boolean)}
$('#request-build').onclick=()=>{let issues=$('#compatibility strong:not(.ok)');if(issues){showToast('Vui lòng xử lý lỗi tương thích trước khi gửi.');return}$('#contact-build').value='Cấu hình tự chọn';location.hash='contact'};
$('#contact-form').onsubmit=async e=>{e.preventDefault();let form=e.target,data=Object.fromEntries(new FormData(form));data.build=selectedBuild();let message=$('#contact-message');try{if(location.protocol!=='file:'){let response=await fetch('api/orders.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!response.ok)throw new Error('Request failed');}message.textContent='Yêu cầu đã được gửi. Chuyên viên sẽ liên hệ để xác nhận cấu hình cùng bạn.';form.reset();showToast('Đã gửi yêu cầu thành công.')}catch(error){message.textContent='Không thể gửi yêu cầu lúc này. Vui lòng gọi 0901 234 567.';showToast('Gửi yêu cầu thất bại, hãy thử lại.')}}
$('.menu-toggle').onclick=()=>document.querySelector('nav').classList.toggle('open');renderComponents();renderBuilds();renderBuilder();showAdvisorStep();
