CREATE DATABASE IF NOT EXISTS bytebuild CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bytebuild;

CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(120) NOT NULL, email VARCHAR(180), phone VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE admins (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, username VARCHAR(80) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE component_categories (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(60) UNIQUE NOT NULL);
CREATE TABLE brands (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) UNIQUE NOT NULL);
CREATE TABLE components (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category_id INT UNSIGNED NOT NULL, brand_id INT UNSIGNED, name VARCHAR(160) NOT NULL, price DECIMAL(12,2) NOT NULL DEFAULT 0, specs JSON, socket VARCHAR(30), memory_type VARCHAR(30), form_factor VARCHAR(30), wattage INT, clearance_mm INT, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(category_id) REFERENCES component_categories(id), FOREIGN KEY(brand_id) REFERENCES brands(id));
CREATE TABLE builds (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(140) NOT NULL, usage_type VARCHAR(60), description TEXT, estimated_price DECIMAL(12,2), is_featured TINYINT(1) DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE build_components (build_id INT UNSIGNED NOT NULL, component_id INT UNSIGNED NOT NULL, quantity TINYINT UNSIGNED DEFAULT 1, PRIMARY KEY(build_id, component_id), FOREIGN KEY(build_id) REFERENCES builds(id) ON DELETE CASCADE, FOREIGN KEY(component_id) REFERENCES components(id));
CREATE TABLE orders (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED, build_id INT UNSIGNED, status ENUM('Pending','Contacted','Confirmed','Completed','Cancelled') DEFAULT 'Pending', estimated_price DECIMAL(12,2), note TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(build_id) REFERENCES builds(id));
CREATE TABLE order_items (order_id INT UNSIGNED NOT NULL, component_id INT UNSIGNED NOT NULL, quantity TINYINT UNSIGNED DEFAULT 1, price_snapshot DECIMAL(12,2) NOT NULL, PRIMARY KEY(order_id, component_id), FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE, FOREIGN KEY(component_id) REFERENCES components(id));
CREATE TABLE compatibility_rules (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, source_category_id INT UNSIGNED NOT NULL, target_category_id INT UNSIGNED NOT NULL, rule_type VARCHAR(50) NOT NULL, rule_data JSON NOT NULL, FOREIGN KEY(source_category_id) REFERENCES component_categories(id), FOREIGN KEY(target_category_id) REFERENCES component_categories(id));
CREATE TABLE contacts (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(120) NOT NULL, phone VARCHAR(30) NOT NULL, email VARCHAR(180), address VARCHAR(255), note TEXT, build_snapshot JSON, status ENUM('New','Contacted','Closed') DEFAULT 'New', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
